### ISSUE TITLE
Official image and default project template broken

### ISSUE THREAD

**Issue by mgmorcos** [evidence-dev/docker-devenv#9]
Official evidence-dev image does not work with default project template.

Steps to reproduce:

1. `--init` a new project
2. run the evidence-dev container
3. you'll see this error all over the rendered report:

Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /evidence-workspace/node_modules/duckdb/lib/binding/duckdb.node)

Reproduced in multiple environments, most recently Docker Compose running on Debian Buster.

Adding libc6-compat to the image didn't help.

**Comment by AmsellemJoseph** [comment]
Hey, I have the same problem, I'm running on linux/arm64.

Thanks for your responses. 😊

**Comment by ud3sh** [comment]
Thanks for reporting the issue @mgmorcos and @AmsellemJoseph! 

We are still working on a holistic solution that works on all platforms without the image size being too large.  

As a stop gap, we published a new image `evidencedev/devenv:ubuntu` that should let you get around the issue.  
In order to use this image, simply replace where you were using `devenv:latest` in your command line with `devenv:ubuntu` 

e.g if you were running the following to setup your dev env
  `docker run -v=$(pwd):/evidence-workspace -p=3000:3000 -it --rm evidencedev/devenv:latest`
 run it instead with 
   `docker run -v=$(pwd):/evidence-workspace -p=3000:3000 -it --rm evidencedev/devenv:ubuntu`

**Comment by mgmorcos** [comment]
thanks @ud3sh now i see: 
```sh
exec /usr/bin/bash: exec format error
```

**Comment by AmsellemJoseph** [comment]
Hey @ud3sh,
I confirm, in linux/and64 I have the same issue than @mgmorcos.

And when i'm running on linux/arm64, I have this issue:

 ✗ orders_by_month /evidence-workspace/node_modules/duckdb/lib/binding/duckdb.node: cannot open shared object file: No such file or directory.

Thanks a lot for your work and responses. 😊

**Comment by ud3sh** [comment]
Thanks @mgmorcos @AmsellemJoseph.  Really appreciate you looking into this.

Sorry, forgot to build the test image with a multi platform option.  In any case the amd64 image should be up 
<img width="821" alt="CleanShot 2023-10-01 at 16 49 33@2x" src="https://github.com/evidence-dev/docker-devenv/assets/1594000/7bfd1732-11a2-42a6-b678-d12a99a022b5">

Pushed with this [Dockerfile](https://github.com/evidence-dev/docker-devenv/blob/docker-devenv-9/Dockerfile-duckdb) in case you still want to take a look.

RE:
>✗ orders_by_month /evidence-workspace/node_modules/duckdb/lib/binding/duckdb.node: cannot open shared object file: No such file or directory.

@AmsellemJoseph did this work before with duckdb?  I am curious how you are referencing the duckdb file.   We had some setup instructions to access normal database running on a port your local instance on the main README.md file.  i.e something like the snippet one below to access a postgres instance running on the host machine.  

```
## accessing postgres db running on host instance.
{
    "host": "host.docker.internal",
    "database": "yourDBname",
    "port": 5432,
    "user": "yourUsername"
}
```


This was from before we supported duck DB - haven't really given much thought about access a simple file on the host machine.  As you might suspect, this devenv preceeds our support for duckdb and we haven't quite kept it up to date until you mentioned the issue.

**Comment by mgmorcos** [comment]
@ud3sh TY it's working for me now 🙏

**Comment by AmsellemJoseph** [comment]
hey @ud3sh,

my bad, I misconfigured something, maybe missclick 😅.

Thanks a lot for your work, seems to work now.

**Comment by ud3sh** [comment]
@mgmorcos @AmsellemJoseph 
* [evidencedev/devenv](https://hub.docker.com/r/evidencedev/devenv) is now based on ubuntu and supports all DBs *including* Duckdb
* [evidencedev/devenv-lite](https://hub.docker.com/r/evidencedev/devenv-lite) is alpine based and supports all the DBs *excluding* DuckDB.

We will leave `evidencedev/devenv:ubuntu` hanging around for now, but you should be able to use `evidencedev/devenv:latest` going forward after pulling the latest.
